### ISSUE TITLE
Discussing about the validity of adversarial attack

### ISSUE THREAD

**Issue by sh0416** [UCSB-NLP-Chang/TextGrad#1]
Hi, I've just read your new research and deeply thinking about the validity of threat model.

Usually, the threat model is used for defining the semantic equivalence between the original text and the adversarial one.

Actually, in your paper, the threat model (you used the attack budget) is assumed to the ratio of changed word, which is 25%.

While I read the validity of adversarial attack in the appendix, the valid ratio of adversarial text is 43%, which means 57 of adversarial texts are actually semantically flipped.

After reading the validation result in the appendix, I think the attack success rate in Table 2 doesn't make sense because the adversarial example doesn't guarantee that the human will give the same class.

I know you put more weight on fairness in the main experiment..

Is there any other criterion for the threat model such as semantic similarity score or something?

**Comment by hbr690188270** [comment]
Hi, thank you for your suggestion! I totally agree that it would make the evaluation more comprehensive if we can develop some metrics that can accurately filter out adversarial texts that change the semantics. Since automatical evaluation for label preservation is still a common challenge in adversarial attack generation against NLP models, we focus more on how to improve the attack effectiveness given the same attack budget and candidate token generation method. Also, if some metrics can effectively be applied to filter out adversarial texts that change the semantics (e.g., maybe your CLRCMD can help), I believe it could greatly help the evaluation of attack methods.

**Comment by sh0416** [comment]
Hmm.. Ok Thanks for the detailed response.
